### ISSUE TITLE
PokitDok is missing connect() method in v.0.9

### ISSUE THREAD

**Issue by felixchiu** [pokitdok/pokitdok-java#12]
Refer to: https://github.com/pokitdok/pokitdok-java/blob/master/src/main/java/com/pokitdok/PokitDok.java

`PokitDok.java` doesn't contain `connect()` anymore. That mentioned in [Readme](https://github.com/pokitdok/pokitdok-java/blob/master/README.md). Last seen is v0.7. Can you fix that?

**Comment by denisekgosnell** [comment]
We removed the mention in the readme; the initialization of the client is handled in the constructor and does not need a `connect()` method.  Thanks!

https://github.com/pokitdok/pokitdok-java/pull/14
