### ISSUE TITLE
No response from API calls.

### ISSUE THREAD

**Issue by HarshDoug** [pokitdok/pokitdok-java#13]
I am unable to get a response back from the server using the latest code on GitHub. Is there any known issue?

**Comment by denisekgosnell** [comment]
@HarshDoug can you give us some more details?  What call did you make, what was the response? etc.  Thank you!

**Comment by HarshDoug** [comment]
@denisekgosnell Either nothing appears in my console, or I get:

An exception occurred: java.net.UnknownHostException: platform.pokitdok.com: nodename nor servname provided, or not known

Thank you!

**Comment by denisekgosnell** [comment]
@HarshDoug it sounds like you are having DNS lookup problems from the machine where you are running your application code.  Were you stepping through the java quick start? if so, at what step in this process did this occur?

**Comment by HarshDoug** [comment]
yeah, I tried the java quick stop, and other java examples. This is the latest test code I tried to use. I imported all the resources from maven. I took out my id and secret before posting this, but everything else is the same. Do you work for Pokitdok? I was told I can get Slack support. I am asking because I am currently competing in a api completion for my employer.

import java.io.IOException;
import java.util.HashMap;
        import java.util.Map;
        import main.java.com.pokitdok.*;
        import org.json.simple.*;
import org.json.simple.parser.ParseException;

        public class PokitDokTest {
            public static void main(String argv[]) {

            	
            	   try {
              PokitDok pd = new PokitDok("xxxx, "xxxx);
              
        //
             StringBuffer eligibilityRequest = new StringBuffer();
              eligibilityRequest.append("{");
              eligibilityRequest.append("\"member\": {");
              eligibilityRequest.append("\"birth_date\": \"1970-01-01\",");
              eligibilityRequest.append("\"first_name\": \"Jane\",");
              eligibilityRequest.append("\"last_name\": \"Doe\",");
              eligibilityRequest.append("\"id\": \"W000000000\"");
              eligibilityRequest.append("},");
              eligibilityRequest.append("\"provider\": {");
              eligibilityRequest.append("\"first_name\": \"JEROME\",");
              eligibilityRequest.append("\"last_name\": \"AYA-AY\",");
              eligibilityRequest.append("\"npi\": \"1467560003\"");
              eligibilityRequest.append("},");
              eligibilityRequest.append("\"service_types\": [\"health_benefit_plan_coverage\"],");
              eligibilityRequest.append("\"trading_partner_id\": \"MOCKPAYER\"");
              eligibilityRequest.append("}");
        //
              Map eligibilityQuery = (JSONObject) JSONValue.parse(eligibilityRequest.toString());
              Map<String, Object> response = pd.eligibility(eligibilityQuery);
              System.out.println(response);
            }
            catch (Exception e) {
              System.out.println("An exception occurred: " + e.toString());
            }
            	
            }
        }

**Comment by denisekgosnell** [comment]
@HarshDoug yea! I am PD's tech evangelist.  you can join our slack channel here to get more support as well: https://pokitdok-hackathons.slack.com/signup

I am also looking through the code you posted here, let's move to slack so that I can dig in further.

**Comment by denisekgosnell** [comment]
@HarshDoug We realized that this issue was due to our readme stating to use the `connect()` method.  Thank you!  we updated the readme, here: https://github.com/pokitdok/pokitdok-java/pull/14
